# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::Inputs::SendEmailVerificationInput`.
# Please instead update this file by running `bin/tapioca dsl Types::Inputs::SendEmailVerificationInput`.


class Types::Inputs::SendEmailVerificationInput
  sig { returns(T.nilable(::String)) }
  def email; end
end
