import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next Ap joanap",
  description: "Generated by creatdasdase next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* MOCKED HEADER AND SIDE BAR, SHOUDL BE REMOVED: OP-299 & OP-300 */}
        <header className="h-16 bg-red-500 flex-1">
          <div />
        </header>
        <div className="flex">
          <aside className="w-64 bg-red-100 min-h-screen p-6 hidden md:flex">
            <div />
          </aside>
          {children}
        </div>
      </body>
    </html>
  );
}
