source "https://rubygems.org"

# Use main development branch of Rails
gem "rails", github: "rails/rails", branch: "main"
# Use sqlite3 as the database for Active Record
gem "pg", "~> 1.1"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[windows jruby]

# Use the database-backed adapters for Rails.cache and Active Job
gem "solid_cache"
gem "solid_queue"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem "thruster", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "rack-cors"

gem "sorbet-runtime"
group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # Pry
  gem "pry-byebug"
  gem "pry-meta"
  gem "pry-rails", "~> 0.3.9"

  gem "sorbet"
  gem "tapioca", require: false

  gem "rspec", "~> 3.13"

  gem "rspec-rails", "~> 7.0"

  gem "rspec-expectations", "~> 3.13"

  gem "faker", "~> 3.4"
  gem "standard"
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "annotaterb"
  gem "letter_opener"
end

group :test do
  eval_gemfile "../infra/Gemfile.test"
  gem "shoulda-matchers", "~> 6.0"
end

gem "rails_event_store", "~> 2.15.0"

gem "infra", path: "../infra"

gem "httparty", "~> 0.22.0"
gem "jwt"
gem "memery"
gem "oj"

gem "graphql", "~> 2.3"
gem "graphiql-rails"
gem "siwe", "~> 2.0"
gem "action_policy"
gem "action_policy-graphql"

gem "pycall"

gem "sprockets-rails", "~> 3.5"

gem "eth", "~> 0.5.12"

gem "postmark-rails"

gem "dry-container"
gem "dry-auto_inject"

gem "appsignal", "~> 4.4.0"

gem "telegram-bot-ruby"
