# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  update_voting_power:
    class: UpdateAllUsersVotingPowerJob
    schedule: "0 0 * * *" # Runs at midnight every day
    queue: default
