# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::EnsStartDataInput`.
# Please instead update this file by running `bin/tapioca dsl Types::EnsStartDataInput`.


class Types::EnsStartDataInput
  sig { returns(::String) }
  def address; end
end
