# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::GitcoinScoreStartDataInput`.
# Please instead update this file by running `bin/tapioca dsl Types::GitcoinScoreStartDataInput`.


class Types::GitcoinScoreStartDataInput
  sig { returns(::String) }
  def action_type; end
end
