# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::GitcoinScoreCompletionDataInput`.
# Please instead update this file by running `bin/tapioca dsl Types::GitcoinScoreCompletionDataInput`.


class Types::GitcoinScoreCompletionDataInput
  sig { returns(::String) }
  def address; end

  sig { returns(::String) }
  def nonce; end

  sig { returns(::String) }
  def signature; end
end
