# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ClientAuthentication::Configuration::Authentication::AccountRegistered; end
module ClientAuthentication::CreateTest::Authentication::RegisterAccount; end
module Configuration::Govquests::Configuration; end
module ReadModelHandlerTest::PublicOffer::Product; end
