requires:
  - ./test/test_helper
integration: minitest
usage: opensource
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - shared_kernel*
  ignore:
    - shared_kernel::Configuration#call
