# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `keccak` gem.
# Please instead update this file by running `bin/tapioca gem keccak`.


class Digest::Keccak < ::Digest::Base
  def initialize(*_arg0); end

  def block_length; end
  def digest_length; end
  def finish; end
end
