# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby_event_store-transformations` gem.
# Please instead update this file by running `bin/tapioca gem ruby_event_store-transformations`.


# source://ruby_event_store-transformations//lib/ruby_event_store/transformations/version.rb#3
module RubyEventStore; end

# source://ruby_event_store-transformations//lib/ruby_event_store/transformations/version.rb#4
module RubyEventStore::Transformations; end

# source://ruby_event_store-transformations//lib/ruby_event_store/transformations/identity_map.rb#3
class RubyEventStore::Transformations::IdentityMap
  # @return [IdentityMap] a new instance of IdentityMap
  #
  # source://ruby_event_store-transformations//lib/ruby_event_store/transformations/identity_map.rb#4
  def initialize; end

  # source://ruby_event_store-transformations//lib/ruby_event_store/transformations/identity_map.rb#8
  def dump(domain_event); end

  # source://ruby_event_store-transformations//lib/ruby_event_store/transformations/identity_map.rb#24
  def load(record); end
end

# source://ruby_event_store-transformations//lib/ruby_event_store/transformations/version.rb#5
RubyEventStore::Transformations::VERSION = T.let(T.unsafe(nil), String)

# source://ruby_event_store-transformations//lib/ruby_event_store/transformations/with_indifferent_access.rb#9
class RubyEventStore::Transformations::WithIndifferentAccess
  # source://ruby_event_store-transformations//lib/ruby_event_store/transformations/with_indifferent_access.rb#10
  def dump(record); end

  # source://ruby_event_store-transformations//lib/ruby_event_store/transformations/with_indifferent_access.rb#21
  def load(record); end
end
